name:       ScrabbElm-Server
version:    '0.1.0.0'
github:     AHW214/ScrabbElm-Server
license:    BSD3
author:     Troy Hu and Adam Weider
maintainer: adamweider98@gmail.com
copyright:  2020 Troy Hu and Adam Weider

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/AHW214/ScrabbElm-Server#readme>

dependencies:
- aeson
- async
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- http-types
- jwt
- random
- stm
- text
- text-show
- time
- wai
- wai-cors
- wai-websockets
- warp
- websockets
- yaml

default-extensions:
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- TupleSections

library:
  source-dirs: src

executables:
  ScrabbElm-Server:
    main:           Main.hs
    source-dirs:    app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - ScrabbElm-Server

tests:
  ScrabbElm-Server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ScrabbElm-Server
