name: scrabbelm-server
version: 0.1.0.0
github: AHW214/ScrabbElm-Server
license: BSD3
author: Troy Hu and Adam Weider
maintainer: adamweider98@gmail.com
copyright: 2020 Troy Hu and Adam Weider

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/AHW214/ScrabbElm-Server#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0

default-extensions:
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  scrabbelm-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-simple
    - scrabbelm-server

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - scrabbelm-server
    - hspec
